#
# Makefile for the broadcast(TDMB) RF/BB core.
#

obj-$(CONFIG_LGE_BROADCAST)		+= broadcast_tdmb_drv_if.o
obj-$(CONFIG_LGE_BROADCAST)		+= t3900/
#obj-$(CONFIG_LGE_BROADCAST)		+= lg2102/
#obj-$(CONFIG_LGE_BROADCAST)		+= fc8050/
#obj-y		+= broadcast_tdmb_drv_if.o
#obj-y		+= lg2102/
#obj-y		+= fc8050/
