#
# Makefile for the TDMB T3900 drivers.
#

# Each configuration option enables a list of files.
# LGE
obj-$(CONFIG_LGE_BROADCAST)		+= broadcast_t3900_drv_if.o
obj-$(CONFIG_LGE_BROADCAST)		+= broadcast_t3900.o
obj-$(CONFIG_LGE_BROADCAST)		+= tdmb_tunerbbdrv_t3900.o
obj-$(CONFIG_LGE_BROADCAST)		+= INC_INTERFACE.o
obj-$(CONFIG_LGE_BROADCAST)		+= INC_PROCESS.o
obj-$(CONFIG_LGE_BROADCAST)		+= INC_FICDEC.o
obj-$(CONFIG_LGE_BROADCAST)		+= INC_QFIFO.o
obj-$(CONFIG_LGE_BROADCAST)		+= INC_RF_CTRL500.o
#obj-$(CONFIG_LGE_BROADCAST)		+= bbm.o
#obj-$(CONFIG_LGE_BROADCAST)		+= fc8050_bb.o
#obj-$(CONFIG_LGE_BROADCAST)		+= fc8050_demux.o
#obj-$(CONFIG_LGE_BROADCAST)		+= fc8050_hpi.o
#obj-$(CONFIG_LGE_BROADCAST)		+= fc8050_i2c.o
#obj-$(CONFIG_LGE_BROADCAST)		+= fc8050_isr.o
#obj-$(CONFIG_LGE_BROADCAST)		+= fc8050_ppi.o
#obj-$(CONFIG_LGE_BROADCAST)		+= fc8050_spi.o
#obj-$(CONFIG_LGE_BROADCAST)		+= fc8050_tun.o
#obj-$(CONFIG_LGE_BROADCAST)		+= fci_hal.o
#obj-$(CONFIG_LGE_BROADCAST)		+= fci_i2c.o
#obj-$(CONFIG_LGE_BROADCAST)		+= fci_oal.o
#obj-$(CONFIG_LGE_BROADCAST)		+= fci_tun.o
#obj-y		+= broadcast_fc8050_drv_if.o
#obj-y		+= broadcast_fc8050.o
#obj-y		+= tdmb_tunerbbdrv_fc8050.o
#obj-y		+= bbm.o
#obj-y		+= fc8050_bb.o
#obj-y		+= fc8050_demux.o
#obj-y		+= fc8050_hpi.o
#obj-y		+= fc8050_i2c.o
#obj-y		+= fc8050_isr.o
#obj-y		+= fc8050_ppi.o
#obj-y		+= fc8050_spi.o
#obj-y		+= fc8050_tun.o
#obj-y		+= fci_hal.o
#obj-y		+= fci_i2c.o
#obj-y		+= fci_oal.o
#obj-y		+= fci_tun.o